services:
  frontend:
    container_name: shortify-frontend
    build:
      context: frontend/.
      args:
        - VITE_API_URL=http://127.0.0.1:5000
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
  backend:
    container_name: shortify-backend
    build:
      context: backend/.
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
  database:
    container_name: shortify-database
    image: postgres
    volumes:
      - /shortify/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shortify
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
